name: prevent-file-change
on:
  pull_request:
    branches:
      - '*-ee'
jobs:
  prevent-file-change:
    if: github.head_ref != 'main' && !startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: xalvarez/prevent-file-change-action@v1
        name: Prevent file change
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: ^(?!.*_ee\.go$)(?!.*_ee_test\.go$)(?!.*_ee\.yml$)(?!.*_rel\.go$)(?!.*_rel_test\.go$)(?!go\.mod$)(?!go\.sum$)(?!\.github\/workflows\/check-pr-files\.yml$)(?!vendor\/.*)(?!.*_qa\.go$).*
          trustedAuthors: xalvarez

  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Check commit authors
        run: |
          # 获取所有提交的作者
          authors=$(git log --pretty=format:"%an" origin/main..HEAD)

          # 检查是否包含不允许的用户
          if echo "$authors" | grep -q "root"; then
            echo "Error: root has made a commit in this PR."
            exit 1
          fi